---
title: "Sanity checks"
output:
  pdf_document: default
  html_document: default
---

# Sanity check data graphically

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(ggrepel)
source("read-data.R")
```

```{r}
df <- read.data()
```

N.B.:

   * Shoji is fine.
   * Mathalone is fine.
   * Liu is fine.

# Summary plot.

```{r fig.width = 10, fig.height = 10}
ggplot(df, aes(x = PreOpEyes, y = 
                 ifelse(!is.na(LastPeriodIOPMean) & !is.na(PreOpIOPMean), 
                        LastPeriodIOPMean - PreOpIOPMean,
                        ifelse(!is.na(LastPeriodAbsIOPChangeMean),
                               LastPeriodAbsIOPChangeMean,
                               ifelse(!is.na(OneYAbsIOPChangeMean),
                                      OneYAbsIOPChangeMean,
                                      OneYIOPMean - PreOpIOPMean
                                      )))
                               , label = study.name, color = subtype)) + 
  geom_point() + ylab('IOP change last period') + geom_text_repel()
```

Check that changes add up.

```{r fig.width=6, fig.height=5}
ggplot(df, aes(x = SixMoIOPMean - PreOpIOPMean, y = SixMoAbsIOPChangeMean, label = study.name)) + 
  geom_abline() + 
  geom_point(color="red") + 
  geom_text_repel()
```

```{r fig.width=6, fig.height=5}
ggplot(df, aes(x = OneYIOPMean - PreOpIOPMean, y = OneYAbsIOPChangeMean, label = study.name)) + 
  geom_abline() + 
  geom_point(color="red") + 
  geom_text_repel()
```

```{r fig.width=6, fig.height=5}
ggplot(df, aes(x = LastPeriodIOPMean - PreOpIOPMean, y = LastPeriodAbsIOPChangeMean, label = study.name)) + 
  geom_abline() + 
  geom_point(color="red") + 
  geom_text_repel()
```


Check the relationship between RxPreOpMean and s.d.
```{r}
ggplot(df, aes(x = RxPreOpMean, y = RxPreOpStdDev)) + 
  geom_point() + 
  coord_cartesian(y=c(0, 1.5)) + 
  stat_function(fun = function(x) sqrt((x - floor(x)) * (1 - (x - floor(x)))), color="gray70")
```

```{r}
ggplot(df, aes(x = RxPostOpMean, y = RxPostOpStdDev)) + geom_point() + 
  stat_function(fun = function(x) sqrt((x - floor(x)) * (1 - (x - floor(x)))), color="gray70")
```

Examine loss at one year.

```{r fig.width=6, fig.height=5}
ggplot(df, aes(x=PreOpEyes, y=OneYEyes, label=study.name)) + 
  geom_point(color="red") + 
  geom_abline() + 
  geom_text_repel() + coord_fixed()
```

```{r fig.width=6, fig.height=5}
ggplot(df, aes(x=OneYEyes / PreOpEyes, label=study.name)) + 
  geom_histogram() + 
  coord_cartesian()
```

```{r}
ggplot(df, aes(x=subtype, fill=MIGsYorN)) + 
  geom_histogram(stat="count", position = 'dodge')
```

Look at the distribution of eyes and IOP means. 

```{r}
ggplot(df, aes(x=PreOpEyes, y=PreOpIOPMean)) + geom_point()
```

Look at number of eyes and standard deviation.

```{r fig.width=11, fig.height=11}
ggplot(df, aes(x=PreOpEyes, y=PreOpIOPStdDev, label=study.name)) + 
  geom_point(color="red") + geom_text_repel(nudge_x = 5)
```

```{r fig.width=5, fig.height=5}
ggplot(df, aes(x=PreOpEyes, y=SixMoAbsIOPChangeStdDev, label=study.name)) + 
  geom_point(color="red") + geom_text_repel(nudge_x = 5)
```

```{r fig.width=5, fig.height=5}
ggplot(df, aes(x=PreOpEyes, y=SixMoIOPStdDev, label=study.name)) + 
  geom_point(color="red") + geom_text_repel(nudge_x = 5)
```

```{r fig.width=5, fig.height=5}
ggplot(df, aes(x=PreOpEyes, y=OneYAbsIOPChangeStdDev, label=study.name)) + 
  geom_point(color="red") + geom_text_repel(nudge_x = 5)
```

```{r fig.width=5, fig.height=5}
ggplot(df, aes(x=PreOpEyes, y=OneYIOPStdDev, label=study.name)) + 
  geom_point(color="red") + geom_text_repel(nudge_x = 5)
```

```{r fig.width=5, fig.height=5}
ggplot(df, aes(x=PreOpEyes, y=LastPeriodAbsIOPChangeStdDev, label=study.name)) + 
  geom_point(color="red") + geom_text_repel(nudge_x = 5)
```

```{r fig.width=5, fig.height=5}
ggplot(df, aes(x=PreOpEyes, y=SixMoIOPStdDev, label=study.name)) + 
  geom_point(color="red") + geom_text_repel(nudge_x = 5)
```
